apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres  # Это должно совпадать с label в StatefulSet или Deployment
  ports:
    - port: 5432
      targetPort: 5432
