apiVersion: apps/v1
kind: Deployment
metadata:
  name: task4-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task4
  template:
    metadata:
      labels:
        app: task4
    spec:
      containers:
      - name: nginx
        image: task4-image:v1
        ports:
        - containerPort: 80