version: '3.8'

services:
  web:
    build: ./app/
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - mynetwork

networks:
  mynetwork:
