version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: newsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - news-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - DB_HOST=postgres
      - DB_NAME=newsdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - news-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - news-network
    restart: always

networks:
  news-network:
    driver: bridge

volumes:
  postgres-data:
